# 4. Criar arquivos de configuração para Vercel
vercel_json = """{
  "framework": null,
  "public": true,
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}"""

package_json = """{
  "name": "recanto-arquitetura",
  "version": "1.0.0",
  "description": "Site institucional Recanto - Arquitetura Contemporânea",
  "main": "index.html",
  "scripts": {
    "dev": "python -m http.server 3000",
    "build": "echo 'Build completed'"
  },
  "keywords": ["arquitetura", "design", "contemporaneo"],
  "author": "Recanto Arquitetura",
  "license": "MIT"
}"""

gitignore = """# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node_modules folder
node_modules/

# npm cache
.npm

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# next.js build output
.next

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# Vercel
.vercel

# MacOS
.DS_Store

# Windows
Thumbs.db

# Build folder
build/
dist/"""

readme_md = """# Recanto - Arquitetura Contemporânea

Site institucional para o escritório Recanto - Arquitetura Contemporânea.

## 🎨 Características

- **Design Responsivo**: Adaptado para desktop, tablet e mobile
- **Paleta de Cores**: Bege claro (#FFF7F0) e Marrom (#61452B)
- **Tipografia**: Compagnon Medium (com fallback Georgia, serif)
- **Navegação Suave**: Entre seções com scroll otimizado
- **Modais Interativos**: Para detalhes dos projetos
- **Formulário Funcional**: Sistema de contato completo

## 📁 Estrutura do Projeto

```
recanto-arquitetura/
├── index.html              # Página principal
├── css/
│   └── style.css           # Estilos CSS
├── js/
│   └── script.js           # JavaScript
├── images/                 # Pasta para imagens (35 arquivos)
├── package.json            # Configurações do projeto
├── vercel.json             # Configuração do Vercel
├── .gitignore             # Arquivos ignorados pelo Git
├── README.md              # Este arquivo
├── LISTA_IMAGENS.md       # Lista completa das imagens
└── DEPLOY_VERCEL.md       # Instruções de deploy

```

## 🚀 Como usar

1. **Baixe todos os arquivos** e mantenha a estrutura de pastas
2. **Adicione as 35 imagens** na pasta `images/` conforme `LISTA_IMAGENS.md`
3. **Abra o `index.html`** em um navegador para visualizar localmente
4. **Para deploy no Vercel**, siga as instruções em `DEPLOY_VERCEL.md`

## 📱 Seções do Site

1. **HOME**: Logo principal, título outline e texto filosófico
2. **SOBRE**: Fotos dos sócios e texto institucional  
3. **MÉTODO**: 5 etapas do processo com círculos para imagens
4. **PROJETOS**: Grid de 6 projetos com modais detalhados
5. **CONTATO**: Formulário e informações de contato
6. **RODAPÉ**: Copyright e call-to-action

## 🎯 Funcionalidades

- ✅ Menu responsivo com hamburger para mobile
- ✅ Navegação suave entre seções
- ✅ Modais com galeria de 4 fotos por projeto
- ✅ Sistema de avaliação com 5 estrelas
- ✅ Formulário com validação HTML5
- ✅ Alternância de cores entre seções
- ✅ Animações CSS suaves
- ✅ Design mobile-first

## 🛠️ Tecnologias

- **HTML5**: Estrutura semântica
- **CSS3**: Flexbox, Grid, animações
- **JavaScript**: Vanilla JS, sem dependências
- **Responsive Design**: Mobile-first approach

## 📞 Contato

- **WhatsApp**: 12996462826
- **Email**: recantomineiroarquitetura@gmail.com
- **Endereço**: Av. João Pinheiro, 607
- **Instagram**: @recanto_arq

---
© 2025 Recanto Arquitetura Ltda. - Entre em contato para transformar seu sonho em realidade"""

# Salvar arquivos de configuração
with open('vercel.json', 'w', encoding='utf-8') as f:
    f.write(vercel_json)

with open('package.json', 'w', encoding='utf-8') as f:
    f.write(package_json)

with open('.gitignore', 'w', encoding='utf-8') as f:
    f.write(gitignore)

with open('README.md', 'w', encoding='utf-8') as f:
    f.write(readme_md)

print("✅ Arquivos de configuração criados com sucesso!")